/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BasicSet: typeof import('./src/components/settools/BasicSet.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Index: typeof import('./src/components/Index.vue')['default']
    InitSetPwd: typeof import('./src/components/settools/InitSetPwd.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    SettingDialog: typeof import('./src/components/SettingDialog.vue')['default']
    ShortcutKeys: typeof import('./src/components/settools/ShortcutKeys.vue')['default']
    Support: typeof import('./src/components/settools/Support.vue')['default']
    UpdatePwd: typeof import('./src/components/settools/UpdatePwd.vue')['default']
  }
}
